import fetchURL from "../../utils/fetchURL";
import { FetchOptions, SimpleAdapter } from "../../adapters/types";
import { CHAIN } from "../../helpers/chains";
import { getUniqStartOfTodayTimestamp } from "../../helpers/getUniSubgraphVolume";

const methodology = {
  Fees: "Fees generated by Volo vaults including performance fees and deposit/withdrawal fees.",
  ProtocolRevenue:
    "Performance fee revenue earned by Volo protocol from vault operations.",
};

const fetchData = () => {
  return async ({ startTimestamp, endTimestamp }: FetchOptions) => {
    const dailyFeesData = (
      await fetchURL(
        `https://open-api.naviprotocol.io/api/volo/volo-vaults?type=fees&timestamp=${
          new Date(endTimestamp * 1000).toISOString().split("T")[0]
        }`
      )
    ).data;

    const dailyRevenueData = (
      await fetchURL(
        `https://open-api.naviprotocol.io/api/volo/volo-vaults?type=revenue&timestamp=${
          new Date(endTimestamp * 1000).toISOString().split("T")[0]
        }`
      )
    ).data;

    const dayTimestamp = getUniqStartOfTodayTimestamp(
      new Date(endTimestamp * 1000)
    );

    const dailyFees = Object.values(dailyFeesData).reduce(
      (sum: number, fee: any) => sum + fee,
      0
    );
    const dailyRevenue = Object.values(dailyRevenueData).reduce(
      (sum: number, revenue: any) => sum + revenue,
      0
    );

    return {
      dailyFees: dailyFees,
      dailyRevenue: dailyRevenue,
      dailyProtocolRevenue: dailyRevenue,
      timestamp: dayTimestamp,
    };
  };
};

const adapter: SimpleAdapter = {
  version: 2,
  adapter: {
    [CHAIN.SUI]: {
      fetch: fetchData(),
      start: "2024-12-17",
      meta: {
        methodology,
      },
    },
  },
};

export default adapter;
